adjective = input("Enter an adjective: ")
object = input("Enter an object: ")
imaginary_friend = input("Enter the name of an imaginary friend: ")
adjective = input("Enter another adjective: ")
verb = input("Enter a verb: ")

print("          Under The Bridge")
print("Sometimes I feel like " + adjective )
print("I don't have a " + object )
print("Sometimes I feel like my only friend is " + imaginary_friend )
print("The " + adjective + " city ")
print("Lonely as I am, together we " + verb )
