name = input("Enter your name: ")
date = input("Enter a date: ")
last_name = input("Enter a last name: ")
noun = input("Enter a noun: ")
letter = input("Enter a letter: ")
noun = input("Enter a 3 letter noun: ")
letter = input("Enter another letter: ")
noun = input("Enter another 3 letter noun: ")
noun = input("Enter a noun: ")
plural_noun = input("Enter a plural noun: ")
letter = input("Enter another letter: ")
noun = input("Enter another 3 letter noun: ")
letter = input("Enter another letter: ")
noun = input("Enter another 3 letter noun: ")
sound = input("Enter a sound: ")
sound = input("Enter a sound: ")
sound = input("Enter a sound: ")
sound = input("Enter a sound: ")
sound = input("Enter a sound: ")
sound = input("Enter a sound: ")
letter = input("Enter another letter: ")
noun = input("Enter another 3 letter noun: ")
letter = input("Enter another letter: ")
noun = input("Enter another 3 letter noun: ")

print("Name: " + name )
print("Date: " + date )

print(         x"Big Mac Who?")
print("Big Mc " + last_name + " had a " + noun + ",")
print(letter + "- " + noun + ", " + letter + "- " + noun + " O.")

print("On this " + noun + " he had some " + plural_noun + ", " + letter + " -3 " + noun + ", " + letter + "- " + noun + " O.")

print("With a " + sound + ", " + sound + " here, and a " + sound + " " + sound + " there, everywhere a " + sound + "- " + sound + " " + letter + "- " + noun + ", " + letter + "- " + noun + " O.")
