adjective = input("Enter an adjective: ")
adjective = input("Enter another adjective: ")
noun = input("Enter a noun: ")
verb = input("Enter a verb in singular present form: ")
fruit = input("Enter a fruit: ")
noun = input("Enter another noun: ")
fruit = input("Enter another fruit: ")
object = input("Enter an object: ")
animal = input("Enter an animal: ")
adjective = input("Enter another adjective: ")
plural_noun = input("Enter a plural noun: ")

print("              The Rose Family")
print("The rose is a " + adjective + ",")
print("And was always a " + adjective + ".")
print("But the " + noun + " now " + verb )
print("That the " + fruit + " is a " + noun + ",")
print("And the " + fruit + " is, and so is ")
print("The " + object + ", I suppose.")
print("The " + animal + " only knows")
print("What will next prove a rose " + adjective + ".")
print(plural_noun + " , of course, are a rose -")
print("But were always a rose.")
