name = input("Enter a name: ")
date = input("Enter a date: ")
plural_noun = input("Enter a plural noun: ")
plural_noun = input("Enter another plural noun: ")
verb = input("Enter a verb: ")
celebrity = ("Enter the name of a celebrity: ")
noun = input("Enter a noun: ")
ing = input("Enter a verb ending in 'ing': ")
plural_noun = input("Enter another plural noun: ")
noun = input("Enter another noun: ")
plural_noun = input("Enter another plural noun: ")

print("Name: " + name)
print("Date: " + date)
print("          At The Arcade!")
print("When I go to the arcade with my " + plural_noun + " there are lots of games to play.")
print("I spend lots of time there with my friends. In 'Xmen' you can be different " + plural_noun + ".")
print("The point of the game is to " + verb + " every robot.")
print("You also need to save people, and then you can go to the next level. In 'Star Wars' you are " + celebrity + " and you try to destroy every " + noun + ".")
print("In a car racing / motorcycle racing game you need to beat every computerized vehicle that you are " + ing + " against.")
print("There are a whole lot of other cool games. When you play some games you win " + plural_noun + " for certain scores.")
print("Once you're done you can cash in your tickets to get a big " + noun + ".")
print("You can save your " + plural_noun + " for another time.")
print("When I went to this arcade I didn't believe how much fun it would be. You might annoy your parents by asking them over and over if you can go back to there. So far I have had a lot of fun every time I've been to this great arcade!")

